#!/usr/bin/env node
/**
 * Compiles MJML email templates into a TypeScript module with template strings.
 * Uses the mjml CLI via child_process to avoid needing mjml as a dependency.
 *
 * Run: node scripts/compile-emails.mjs
 * Requires: npx mjml must be available
 */
import { writeFileSync, readdirSync } from 'fs';
import { join, basename, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const emailsDir = join(__dirname, '..', 'src', 'emails');
const outputFile = join(emailsDir, 'templates.ts');

const mjmlFiles = readdirSync(emailsDir).filter((f) => f.endsWith('.mjml'));

let output = `// Auto-generated by scripts/compile-emails.mjs — do not edit manually\n\n`;

for (const file of mjmlFiles) {
  const name = basename(file, '.mjml')
    .replace(/-([a-z])/g, (_, c) => c.toUpperCase()); // kebab-case → camelCase

  const filePath = join(emailsDir, file);
  const html = execSync(`npx mjml "${filePath}" --config.minify true`, {
    encoding: 'utf-8',
    stdio: ['pipe', 'pipe', 'pipe'],
  }).trim()
    // Strip the <!-- FILE: /path/to/... --> comment that leaks build paths
    .replace(/^<!--\s*FILE:.*?-->\n?/, '');

  // Escape backticks and ${} in the HTML for template literal safety
  const escaped = html
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  output += `export const ${name}Html = \`${escaped}\`;\n\n`;
}

writeFileSync(outputFile, output);
console.log(`Compiled ${mjmlFiles.length} email templates → ${outputFile}`);
