[default]
airtable_base_id = "appmCFCuFmxkvO1zc"
airtable_events_table_id = "tblf7gxCB41f6PaPf"
airtable_users_table_id = "tblwoiggOeX0s6nyG"
airtable_projects_table_id = "tbl0mqJURRV5VpkIj"
airtable_referrals_table_id = "tblHPIrWpu4IYrIm0"
airtable_votes_table_id = "tbl0OfcZu5TWs2j19"
production_url = "https://podium.hackclub.com"
loops_transactional_id = "cmg1hjhed4xyi0r0ijvfyyqa1"

[development]
airtable_base_id = "appec7U14eWSv08R4"
airtable_events_table_id = "tblaEI2ed9JMR5Lep"
airtable_users_table_id = "tblf4zw9j8JhxBWdb"
airtable_projects_table_id = "tbl9YL1Au1MtPzAiq"
airtable_referrals_table_id = "tblU0VGfBD7vy2kUK"
airtable_votes_table_id = "tblWcPEiD9cxaeN8O"
production_url = "http://localhost:5173"
review_factory_url = "http://localhost:8001"