# .github/workflows/test.yml
# Draft CI config for Postgres-based tests

name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test
          POSTGRES_DB: podium_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      DATABASE_URL: postgresql+asyncpg://postgres:test@localhost:5432/podium_test
      PODIUM_ENV: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install uv
        run: pip install uv
      
      - name: Install dependencies
        working-directory: backend
        run: uv sync
      
      - name: Run migrations
        working-directory: backend
        run: uv run alembic upgrade head
      
      # Note: We use Playwright for frontend E2E tests, not pytest
      # Add frontend test steps here when ready
