---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podium.fullname" . }}-auth
  labels:
    {{- include "podium.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  replicas: {{ .Values.authService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "podium.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "podium.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: auth-service
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: auth-service
          image: {{ include "podium.image" (dict "root" . "svc" .Values.authService "name" "auth-service") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.authService.port }}
              protocol: TCP
          env:
            {{- include "podium.commonEnv" . | nindent 12 }}
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "podium.fullname" . }}-config
                  key: AWS_REGION
            - name: SES_FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "podium.fullname" . }}-config
                  key: SES_FROM_EMAIL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "podium.fullname" . }}-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "podium.fullname" . }}-secrets
                  key: AWS_SECRET_ACCESS_KEY
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.authService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "podium.fullname" . }}-auth
  labels:
    {{- include "podium.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "podium.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth-service
  ports:
    - name: http
      port: {{ .Values.authService.port }}
      targetPort: http
      protocol: TCP
