apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podium.fullname" . }}-secrets
  labels:
    {{- include "podium.labels" . | nindent 4 }}
type: Opaque
stringData:
  PODIUM_DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  PODIUM_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  R2_ACCOUNT_ID: {{ .Values.secrets.r2AccountId | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.secrets.r2AccessKeyId | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.secrets.r2SecretAccessKey | quote }}
