// This file is auto-generated by @hey-api/openapi-ts

export type AuthenticatedUser = {
    access_token: string;
    token_type: string;
    user: UserPrivate;
};

export type Body_remove_attendee_events_admin__event_id__remove_attendee_post = {
    user_id: string;
};

export type CreateVotes = {
    projects: Array<(string)>;
    event: string;
};

/**
 * Private event info - visible to owner and attendees.
 */
export type EventPrivate = {
    id: string;
    name: string;
    slug: string;
    description: string;
    votable: boolean;
    leaderboard_enabled: boolean;
    demo_links_optional: boolean;
    max_votes_per_user: number;
    owner_id: string;
    ysws_checks_enabled: boolean;
};

/**
 * Public event info - visible to anyone.
 */
export type EventPublic = {
    id: string;
    name: string;
    slug: string;
    description: string;
    votable: boolean;
    leaderboard_enabled: boolean;
    demo_links_optional: boolean;
    max_votes_per_user: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Request body for creating a project.
 */
export type ProjectCreate = {
    name: string;
    repo: string;
    image_url: string;
    demo?: string;
    description?: string;
    hours_spent?: number;
    event_id: string;
};

/**
 * Private project info - visible to owner and collaborators.
 */
export type ProjectPrivate = {
    id: string;
    name: string;
    repo: string;
    image_url: string;
    demo: string;
    description: string;
    points: number;
    owner_id: string;
    join_code: string;
    hours_spent: number;
    event_id: string;
};

/**
 * Public project info - visible to anyone.
 */
export type ProjectPublic = {
    id: string;
    name: string;
    repo: string;
    image_url: string;
    demo: string;
    description: string;
    points: number;
    owner_id: string;
};

/**
 * Request body for updating a project. All fields optional.
 */
export type ProjectUpdate = {
    name?: (string | null);
    repo?: (string | null);
    image_url?: (string | null);
    demo?: (string | null);
    description?: (string | null);
    hours_spent?: (number | null);
};

export type ReferralResponse = {
    id: string;
    content: string;
    user_id: string;
    event_id: string;
};

/**
 * Request body for creating a test event.
 */
export type TestEventCreate = {
    name: string;
    description?: string;
};

export type UserAttendee = {
    id: string;
    email: string;
    display_name: string;
    first_name: string;
    last_name: string;
};

export type UserEvents = {
    attending_events: Array<EventPublic>;
};

export type UserExistsResponse = {
    exists: boolean;
};

export type UserLoginPayload = {
    email: string;
};

/**
 * Private user info - visible to the user themselves and event owners.
 */
export type UserPrivate = {
    id: string;
    display_name: string;
    email: string;
    first_name: string;
    last_name: string;
    phone?: string;
};

/**
 * Public user info - visible to anyone.
 */
export type UserPublic = {
    id: string;
    display_name: string;
};

/**
 * Request body for user signup.
 */
export type UserSignup = {
    email: string;
    first_name: string;
    last_name?: (string | null);
    display_name?: (string | null);
    phone?: (string | null);
    street_1?: (string | null);
    street_2?: (string | null);
    city?: (string | null);
    state?: (string | null);
    zip_code?: (string | null);
    country?: (string | null);
    dob?: (string | null);
};

/**
 * Request body for updating user profile. All fields optional.
 */
export type UserUpdate = {
    display_name?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    phone?: (string | null);
    street_1?: (string | null);
    street_2?: (string | null);
    city?: (string | null);
    state?: (string | null);
    zip_code?: (string | null);
    country?: (string | null);
    dob?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ValidationResult = {
    valid: boolean;
    message: string;
};

export type VoteResponse = {
    id: string;
    voter_id: string;
    project_id: string;
    event_id: string;
};

export type RequestLoginRequestLoginPostData = {
    body: UserLoginPayload;
    query: {
        redirect: string;
    };
};

export type RequestLoginRequestLoginPostResponse = (unknown);

export type RequestLoginRequestLoginPostError = (HTTPValidationError);

export type VerifyTokenVerifyGetData = {
    query: {
        token: string;
    };
};

export type VerifyTokenVerifyGetResponse = (AuthenticatedUser);

export type VerifyTokenVerifyGetError = (HTTPValidationError);

export type ListOfficialEventsEventsOfficialGetResponse = (Array<EventPublic>);

export type ListOfficialEventsEventsOfficialGetError = unknown;

export type GetEventEndpointEventsEventIdGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventEndpointEventsEventIdGetResponse = (EventPublic);

export type GetEventEndpointEventsEventIdGetError = (HTTPValidationError);

export type GetAttendingEventsEventsGetResponse = (UserEvents);

export type GetAttendingEventsEventsGetError = unknown;

export type AttendEventEventsEventIdAttendPostData = {
    path: {
        event_id: string;
    };
};

export type AttendEventEventsEventIdAttendPostResponse = (unknown);

export type AttendEventEventsEventIdAttendPostError = (HTTPValidationError);

export type VoteEventsVotePostData = {
    body: CreateVotes;
};

export type VoteEventsVotePostResponse = (unknown);

export type VoteEventsVotePostError = (HTTPValidationError);

export type GetEventProjectsEventsEventIdProjectsGetData = {
    path: {
        event_id: string;
    };
    query: {
        /**
         * Sort by points if true
         */
        leaderboard: boolean;
    };
};

export type GetEventProjectsEventsEventIdProjectsGetResponse = (Array<ProjectPublic>);

export type GetEventProjectsEventsEventIdProjectsGetError = (HTTPValidationError);

export type GetAtIdEventsIdSlugGetData = {
    path: {
        slug: string;
    };
};

export type GetAtIdEventsIdSlugGetResponse = (string);

export type GetAtIdEventsIdSlugGetError = (HTTPValidationError);

export type CreateTestEventEventsTestCreatePostData = {
    body: TestEventCreate;
};

export type CreateTestEventEventsTestCreatePostResponse = (EventPublic);

export type CreateTestEventEventsTestCreatePostError = (HTTPValidationError);

export type GetEventAdminEventsAdminEventIdGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventAdminEventsAdminEventIdGetResponse = (EventPrivate);

export type GetEventAdminEventsAdminEventIdGetError = (HTTPValidationError);

export type GetEventAttendeesEventsAdminEventIdAttendeesGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventAttendeesEventsAdminEventIdAttendeesGetResponse = (Array<UserAttendee>);

export type GetEventAttendeesEventsAdminEventIdAttendeesGetError = (HTTPValidationError);

export type RemoveAttendeeEventsAdminEventIdRemoveAttendeePostData = {
    body: Body_remove_attendee_events_admin__event_id__remove_attendee_post;
    path: {
        event_id: string;
    };
};

export type RemoveAttendeeEventsAdminEventIdRemoveAttendeePostResponse = (unknown);

export type RemoveAttendeeEventsAdminEventIdRemoveAttendeePostError = (HTTPValidationError);

export type GetEventLeaderboardEventsAdminEventIdLeaderboardGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventLeaderboardEventsAdminEventIdLeaderboardGetResponse = (Array<ProjectPrivate>);

export type GetEventLeaderboardEventsAdminEventIdLeaderboardGetError = (HTTPValidationError);

export type GetEventVotesEventsAdminEventIdVotesGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventVotesEventsAdminEventIdVotesGetResponse = (Array<VoteResponse>);

export type GetEventVotesEventsAdminEventIdVotesGetError = (HTTPValidationError);

export type GetEventReferralsEventsAdminEventIdReferralsGetData = {
    path: {
        event_id: string;
    };
};

export type GetEventReferralsEventsAdminEventIdReferralsGetResponse = (Array<ReferralResponse>);

export type GetEventReferralsEventsAdminEventIdReferralsGetError = (HTTPValidationError);

export type GetProjectsProjectsMineGetResponse = (Array<ProjectPrivate>);

export type GetProjectsProjectsMineGetError = unknown;

export type CreateProjectProjectsPostData = {
    body: ProjectCreate;
};

export type CreateProjectProjectsPostResponse = (unknown);

export type CreateProjectProjectsPostError = (HTTPValidationError);

export type JoinProjectProjectsJoinPostData = {
    query: {
        /**
         * Project join code
         */
        join_code: string;
    };
};

export type JoinProjectProjectsJoinPostResponse = (unknown);

export type JoinProjectProjectsJoinPostError = (HTTPValidationError);

export type UpdateProjectProjectsProjectIdPutData = {
    body: ProjectUpdate;
    path: {
        project_id: string;
    };
};

export type UpdateProjectProjectsProjectIdPutResponse = (unknown);

export type UpdateProjectProjectsProjectIdPutError = (HTTPValidationError);

export type DeleteProjectProjectsProjectIdDeleteData = {
    path: {
        project_id: string;
    };
};

export type DeleteProjectProjectsProjectIdDeleteResponse = (unknown);

export type DeleteProjectProjectsProjectIdDeleteError = (HTTPValidationError);

export type GetProjectEndpointProjectsProjectIdGetData = {
    path: {
        project_id: string;
    };
};

export type GetProjectEndpointProjectsProjectIdGetResponse = (ProjectPublic);

export type GetProjectEndpointProjectsProjectIdGetError = (HTTPValidationError);

export type ValidateProjectProjectsValidatePostData = {
    query: {
        /**
         * Project ID to validate
         */
        project_id: string;
    };
};

export type ValidateProjectProjectsValidatePostResponse = (ValidationResult);

export type ValidateProjectProjectsValidatePostError = (HTTPValidationError);

export type UserExistsUsersExistsGetData = {
    query: {
        email: string;
    };
};

export type UserExistsUsersExistsGetResponse = (UserExistsResponse);

export type UserExistsUsersExistsGetError = (HTTPValidationError);

export type GetCurrentUserInfoUsersCurrentGetResponse = (UserPrivate);

export type GetCurrentUserInfoUsersCurrentGetError = unknown;

export type UpdateCurrentUserUsersCurrentPutData = {
    body: UserUpdate;
};

export type UpdateCurrentUserUsersCurrentPutResponse = (UserPrivate);

export type UpdateCurrentUserUsersCurrentPutError = (HTTPValidationError);

export type GetUserPublicUsersUserIdGetData = {
    path: {
        user_id: string;
    };
};

export type GetUserPublicUsersUserIdGetResponse = (UserPublic);

export type GetUserPublicUsersUserIdGetError = (HTTPValidationError);

export type CreateUserUsersPostData = {
    body: UserSignup;
};

export type CreateUserUsersPostResponse = (unknown);

export type CreateUserUsersPostError = (HTTPValidationError);