"""remove_airtable_id_and_event_join_code

Migration ID: 28f961df26a5
Previous: 2b44c8c9a626
Created: 2026-02-11 18:15:32.914464

This file was auto-generated by Alembic. Review the upgrade() and downgrade()
functions before applying. You can edit them if the auto-generated code isn't
exactly right.
"""

from alembic import op
import sqlalchemy as sa


revision = '28f961df26a5'
down_revision = '2b44c8c9a626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop event join_code
    op.drop_constraint(op.f('events_join_code_key'), 'events', type_='unique')
    op.drop_column('events', 'join_code')

    # Drop airtable_id from all tables
    op.drop_index(op.f('ix_events_airtable_id'), table_name='events')
    op.drop_column('events', 'airtable_id')
    op.drop_index(op.f('ix_projects_airtable_id'), table_name='projects')
    op.drop_column('projects', 'airtable_id')
    op.drop_index(op.f('ix_referrals_airtable_id'), table_name='referrals')
    op.drop_column('referrals', 'airtable_id')
    op.drop_index(op.f('ix_users_airtable_id'), table_name='users')
    op.drop_column('users', 'airtable_id')
    op.drop_index(op.f('ix_votes_airtable_id'), table_name='votes')
    op.drop_column('votes', 'airtable_id')


def downgrade() -> None:
    op.add_column('votes', sa.Column('airtable_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_votes_airtable_id'), 'votes', ['airtable_id'], unique=True)
    op.add_column('users', sa.Column('airtable_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_airtable_id'), 'users', ['airtable_id'], unique=True)
    op.add_column('referrals', sa.Column('airtable_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_referrals_airtable_id'), 'referrals', ['airtable_id'], unique=True)
    op.add_column('projects', sa.Column('airtable_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_projects_airtable_id'), 'projects', ['airtable_id'], unique=True)
    op.add_column('events', sa.Column('airtable_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_events_airtable_id'), 'events', ['airtable_id'], unique=True)
    op.add_column('events', sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('events_join_code_key'), 'events', ['join_code'], postgresql_nulls_not_distinct=False)
