"""make_event_join_code_nullable

Migration ID: 2b44c8c9a626
Previous: 86972a653c14
Created: 2026-02-10 15:13:39.661955

This file was auto-generated by Alembic. Review the upgrade() and downgrade()
functions before applying. You can edit them if the auto-generated code isn't
exactly right.
"""

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Required for SQLModel column types


revision = '2b44c8c9a626'
down_revision = '86972a653c14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Make events.join_code nullable."""
    # Make join_code nullable (drop NOT NULL constraint)
    op.alter_column('events', 'join_code',
                    existing_type=sa.String(length=20),
                    nullable=True)


def downgrade() -> None:
    """Revert join_code to non-nullable."""
    # This will fail if there are NULL values, which is expected
    op.alter_column('events', 'join_code',
                    existing_type=sa.String(length=20),
                    nullable=False)
