"""change url fields to text

Migration ID: 68760cdd30c1
Previous: eb4f2bdf228a
Created: 2025-12-29 22:50:20.311641

This file was auto-generated by Alembic. Review the upgrade() and downgrade()
functions before applying. You can edit them if the auto-generated code isn't
exactly right.
"""

from alembic import op
import sqlalchemy as sa


revision = '68760cdd30c1'
down_revision = 'eb4f2bdf228a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.alter_column('projects', 'repo', type_=sa.Text(), existing_type=sa.String(500))
    op.alter_column('projects', 'image_url', type_=sa.Text(), existing_type=sa.String(500))
    op.alter_column('projects', 'demo', type_=sa.Text(), existing_type=sa.String(500))


def downgrade() -> None:
    op.alter_column('projects', 'repo', type_=sa.String(500), existing_type=sa.Text())
    op.alter_column('projects', 'image_url', type_=sa.String(500), existing_type=sa.Text())
    op.alter_column('projects', 'demo', type_=sa.String(500), existing_type=sa.Text())
