"""remove cached_auto_quality

Migration ID: 86972a653c14
Previous: 434e824c2c24
Created: 2026-01-24 16:39:47.913085

This file was auto-generated by Alembic. Review the upgrade() and downgrade()
functions before applying. You can edit them if the auto-generated code isn't
exactly right.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '86972a653c14'
down_revision = '434e824c2c24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_column('projects', 'cached_auto_quality')


def downgrade() -> None:
    op.add_column('projects', sa.Column('cached_auto_quality', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
